[tool.poetry]
name = "tpcac2124"
version = "0.1.0"
description = ""
authors = ["juanNH <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask-MySQL = "^1.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
